apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adr-detection-pvc
spec:
  storageClassName: rook-cephfs	
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi