apiVersion: v1
kind: Pod
metadata:
  name: shiny-deploy-pod
spec:
  restartPolicy: Never
  containers:
    - name: shiny-deploy
      image: rocker/shiny-verse:latest
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      env:
        - name: SHINYAPPS_TOKEN
          valueFrom:
            secretKeyRef:
              name: adr-detection-secrets
              key: SHINYAPPS_TOKEN
        - name: SHINYAPPS_SECRET
          valueFrom:
            secretKeyRef:
              name: adr-detection-secrets
              key: SHINYAPPS_SECRET
      args:
        - |
          # Deploy to shinyapps.io
          export PATH=$PATH:/usr/bin/R
          R -e "install.packages(c('rsconnect', 'RcppTOML', 'crosstalk', 'here', 'lazyeval', 'plotly', 'png', 'reticulate','MASS'), repos = 'https://cran.rstudio.com/')"
          R -e "rsconnect::setAccountInfo(name = 'aidan2b', token = Sys.getenv('SHINYAPPS_TOKEN'), secret = Sys.getenv('SHINYAPPS_SECRET'))"
          R -e "rsconnect::deployApp(appDir = 'data/', appName = 'adr-detection', account = 'aidan2b')"

      resources:
        limits:
          memory: 12Gi
          cpu: 6  # Limit of 6 CPU cores
        requests:
          memory: 12Gi
          cpu: 4  # Request of 4 CPU cores
      volumeMounts:
        - mountPath: /data
          name: adr-detection-pvc
  volumes:
    - name: adr-detection-pvc
      persistentVolumeClaim:
        claimName: adr-detection-pvc
