name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        R -e 'install.packages(c("shiny", "rsconnect"))'

    - name: Deploy to shinyapps.io
      run: |
        R -e 'rsconnect::setAccountInfo(name = "<ACCOUNT_NAME>", token = Sys.getenv("SHINYAPPS_TOKEN"), secret = Sys.getenv("SHINYAPPS_SECRET"))'
        R -e 'rsconnect::deployApp(appDir = "shinyapp/", appName = "your_app_name", account = "<ACCOUNT_NAME>")'
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
