name: Deploy Shinyapp

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Use saved Nautilus data to deploy S
      run: |
        # Apply the Kubernetes configuration
        kubectl apply -f shiny-deploy.yaml
