name: shiny-deploy

on:
  workflow_dispatch:
    inputs:
      medication:
        description: 'Enter medication name:'
        required: true

jobs:
  run_pipeline:
    name: Run Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run pipeline
        run: |
          python run_pipeline.py
        env:
          MEDICATION_NAME: ${{ github.event.inputs.medication }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}

  deploy_shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    needs: run_pipeline
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev
          R -e 'install.packages(c("remotes", "covr", "rsconnect"))'
          
      - name: Deploy to shinyapps.io
        run: |
          R -e 'rsconnect::setAccountInfo(name = "my_shinyapps_account", token = Sys.getenv("SHINYAPPS_TOKEN"), secret = Sys.getenv("SHINYAPPS_SECRET"))'
          R -e 'rsconnect::deployApp(appDir = "shinyapp/", appName = "your_app_name", account = "my_shinyapps_account")'
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
